/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as HospitalDoctorsRouteImport } from './routes/hospital-doctors'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as HospitalOwnerDashboardRouteImport } from './routes/hospital-owner/dashboard'
import { Route as HospitalOwnerDoctorsRouteImport } from './routes/hospital-owner/doctors'
import { Route as SuperAdminCreateOwnerRouteImport } from './routes/super-admin/create-owner'
import { Route as SuperAdminDashboardRouteImport } from './routes/super-admin/dashboard'
import { Route as SuperAdminHospitalsRouteImport } from './routes/super-admin/hospitals'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalDoctorsRoute = HospitalDoctorsRouteImport.update({
  id: '/hospital-doctors',
  path: '/hospital-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalOwnerDashboardRoute = HospitalOwnerDashboardRouteImport.update({
  id: '/hospital-owner/dashboard',
  path: '/hospital-owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalOwnerDoctorsRoute = HospitalOwnerDoctorsRouteImport.update({
  id: '/hospital-owner/doctors',
  path: '/hospital-owner/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminCreateOwnerRoute = SuperAdminCreateOwnerRouteImport.update({
  id: '/super-admin/create-owner',
  path: '/super-admin/create-owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminDashboardRoute = SuperAdminDashboardRouteImport.update({
  id: '/super-admin/dashboard',
  path: '/super-admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperAdminHospitalsRoute = SuperAdminHospitalsRouteImport.update({
  id: '/super-admin/hospitals',
  path: '/super-admin/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/hospital-doctors': typeof HospitalDoctorsRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/hospital-owner/dashboard': typeof HospitalOwnerDashboardRoute
  '/hospital-owner/doctors': typeof HospitalOwnerDoctorsRoute
  '/super-admin/create-owner': typeof SuperAdminCreateOwnerRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/hospitals': typeof SuperAdminHospitalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/hospital-doctors': typeof HospitalDoctorsRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/hospital-owner/dashboard': typeof HospitalOwnerDashboardRoute
  '/hospital-owner/doctors': typeof HospitalOwnerDoctorsRoute
  '/super-admin/create-owner': typeof SuperAdminCreateOwnerRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/hospitals': typeof SuperAdminHospitalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/doctor': typeof DoctorRoute
  '/hospital-doctors': typeof HospitalDoctorsRoute
  '/hospitals': typeof HospitalsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/hospital-owner/dashboard': typeof HospitalOwnerDashboardRoute
  '/hospital-owner/doctors': typeof HospitalOwnerDoctorsRoute
  '/super-admin/create-owner': typeof SuperAdminCreateOwnerRoute
  '/super-admin/dashboard': typeof SuperAdminDashboardRoute
  '/super-admin/hospitals': typeof SuperAdminHospitalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/doctor'
    | '/hospital-doctors'
    | '/hospitals'
    | '/login'
    | '/signup'
    | '/hospital-owner/dashboard'
    | '/hospital-owner/doctors'
    | '/super-admin/create-owner'
    | '/super-admin/dashboard'
    | '/super-admin/hospitals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/doctor'
    | '/hospital-doctors'
    | '/hospitals'
    | '/login'
    | '/signup'
    | '/hospital-owner/dashboard'
    | '/hospital-owner/doctors'
    | '/super-admin/create-owner'
    | '/super-admin/dashboard'
    | '/super-admin/hospitals'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/doctor'
    | '/hospital-doctors'
    | '/hospitals'
    | '/login'
    | '/signup'
    | '/hospital-owner/dashboard'
    | '/hospital-owner/doctors'
    | '/super-admin/create-owner'
    | '/super-admin/dashboard'
    | '/super-admin/hospitals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DoctorRoute: typeof DoctorRoute
  HospitalDoctorsRoute: typeof HospitalDoctorsRoute
  HospitalsRoute: typeof HospitalsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  HospitalOwnerDashboardRoute: typeof HospitalOwnerDashboardRoute
  HospitalOwnerDoctorsRoute: typeof HospitalOwnerDoctorsRoute
  SuperAdminCreateOwnerRoute: typeof SuperAdminCreateOwnerRoute
  SuperAdminDashboardRoute: typeof SuperAdminDashboardRoute
  SuperAdminHospitalsRoute: typeof SuperAdminHospitalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-doctors': {
      id: '/hospital-doctors'
      path: '/hospital-doctors'
      fullPath: '/hospital-doctors'
      preLoaderRoute: typeof HospitalDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-owner/dashboard': {
      id: '/hospital-owner/dashboard'
      path: '/hospital-owner/dashboard'
      fullPath: '/hospital-owner/dashboard'
      preLoaderRoute: typeof HospitalOwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-owner/doctors': {
      id: '/hospital-owner/doctors'
      path: '/hospital-owner/doctors'
      fullPath: '/hospital-owner/doctors'
      preLoaderRoute: typeof HospitalOwnerDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/create-owner': {
      id: '/super-admin/create-owner'
      path: '/super-admin/create-owner'
      fullPath: '/super-admin/create-owner'
      preLoaderRoute: typeof SuperAdminCreateOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/dashboard': {
      id: '/super-admin/dashboard'
      path: '/super-admin/dashboard'
      fullPath: '/super-admin/dashboard'
      preLoaderRoute: typeof SuperAdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/super-admin/hospitals': {
      id: '/super-admin/hospitals'
      path: '/super-admin/hospitals'
      fullPath: '/super-admin/hospitals'
      preLoaderRoute: typeof SuperAdminHospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DoctorRoute: DoctorRoute,
  HospitalDoctorsRoute: HospitalDoctorsRoute,
  HospitalsRoute: HospitalsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  HospitalOwnerDashboardRoute: HospitalOwnerDashboardRoute,
  HospitalOwnerDoctorsRoute: HospitalOwnerDoctorsRoute,
  SuperAdminCreateOwnerRoute: SuperAdminCreateOwnerRoute,
  SuperAdminDashboardRoute: SuperAdminDashboardRoute,
  SuperAdminHospitalsRoute: SuperAdminHospitalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
